# mksrc.py
# Generate Prolog source containing MtG card rules and properties.

import ConfigParser
import os
import string
try:
    import xml.etree.cElementTree as ET
except ImportError:
    import xml.etree.ElementTree as ET
import StringIO


def extract_data(xml):
    setnode = xml.find('set')
    cards = xml.findall('set/cards/card')
    return setnode, cards

def get_files_for_sets(sets, dir, suffix):
    files = os.listdir(dir)
    files = [fn for fn in files if fn.endswith(suffix)]
    if sets:
        files = [fn for fn in files if os.path.splitext(fn)[0] in sets]
    files = [os.path.join(dir, fn) for fn in files]
    return files

def gen_prolog_src(filename):
    print "Loading:", filename
    xml = ET.parse(filename)
    setnode, cards = extract_data(xml)

    # extract set data
    pl_shortname = name_to_prolog_identifier(setnode.find('shortname').text)

    out_filename = "cards_%s.pl" % pl_shortname
    f = open(out_filename, 'w')

    print >> f, "%% Card data for", pl_shortname
    print >> f, "%% Auto-generated by mksrc.py -- do not edit\n"

    print >> f, 'set(%s).' % pl_shortname
    print >> f, 'set_full_name(%s, "%s").' % (
                pl_shortname, setnode.find('name').text)
    print >> f, 'set_num_cards(%s, %s).' % (
                pl_shortname, setnode.find('number_of_cards').text)

    # extract card data
    for cardnode in cards:
        pl_card_name = name_to_prolog_identifier(cardnode.find('name').text)
        print >> f, 'card(%s, %s).' % (pl_shortname, pl_card_name)

    f.close()
    print "Written:", out_filename

VALID_IDENTIFIER_CHARS = string.lowercase + string.digits + "_"

def name_to_prolog_identifier(s):
    s = s.lower()
    s = s.replace(" ", "_")
    chars = [c for c in s if c in VALID_IDENTIFIER_CHARS]
    return string.join(chars, '')

if __name__ == "__main__":

    cp = ConfigParser.ConfigParser()
    cp.read("config.txt")
    xmldir = os.path.expanduser(cp.get('main', 'xmldir'))

    # for now, only generate source for M11
    filenames = get_files_for_sets(["M11"], xmldir, '.xml')

    for filename in filenames:
        gen_prolog_src(filename)

